# Generated by Django 4.1 on 2022-08-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="application_url",
            new_name="application_link",
        ),
    ]
