# Generated by Django 4.1 on 2022-08-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_rename_application_url_application_application_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application", options={"ordering": ["-date_applied"]},
        ),
        migrations.AlterField(
            model_name="application",
            name="date_applied",
            field=models.DateField(blank=True, null=True, verbose_name="date applied"),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("IC", "Incomplete"),
                    ("A", "Applied"),
                    ("I", "Interviewed"),
                    ("O", "Offered"),
                    ("R", "Rejected"),
                ],
                default="IC",
                max_length=2,
            ),
        ),
    ]
