# Generated by Django 4.1 on 2022-08-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_application_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="notes",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("IC", "Incomplete"),
                    ("A", "Applied"),
                    ("I", "Interviewed"),
                    ("O", "Offered"),
                    ("R", "Rejected"),
                ],
                max_length=2,
            ),
        ),
    ]
