# Generated by Django 4.1 on 2022-08-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="date_applied",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
