# Generated by Django 4.1 on 2022-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_application_date_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="date_applied",
            field=models.DateField(blank=True, null=True, verbose_name="date applied"),
        ),
    ]
