# Generated by Django 4.1 on 2022-08-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_alter_application_date_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("IC", "Incomplete"),
                    ("A", "Applied"),
                    ("I", "Interview"),
                    ("O", "Offer"),
                    ("R", "Rejected"),
                ],
                default="IC",
                max_length=2,
            ),
        ),
    ]
